### ISSUE TITLE
Skip rpmrebuild

### ISSUE THREAD

**Issue by a-lyupa** [Samsung/combirepo#14]
@ilya-palachev ,
Is it ok to skip rpmrebuild stage?
What is the correct way to build and install it? I got rpmrebuild.tar with 0 byte size.
Why yum is set instead of zypp with --disable-rpm-patching option enabled?

**Comment by ilya-palachev** [comment]
Unfortunately, I don't remember the details about `rpmrebuild` clearly. 

> Is it ok to skip rpmrebuild stage?

If the use case is at used to be, no.

> What is the correct way to build and install it?

Doesn't we describe it in the `setup.py` script?

> I got rpmrebuild.tar with 0 byte size.

Could you provide more details, with what conditions, with what use case do you get `rpmrebuild.tar` with 0 byte size. Does it happen during `combirepo` Deb package building? Or at `combirepo` runtime?

> Why yum is set instead of zypp with --disable-rpm-patching option enabled?

If I recall correctly, `yum` is more stable that `zypp`. I've tried them both, but due to the C++-to-python bindings, `zypp` is very hard to debug, so I preferred `yum` since it was the only package manager from these two, that I succeeded to make work in the use case.

**Comment by a-lyupa** [comment]
> Doesn't we describe it in the setup.py script?
> Could you provide more details, with what conditions, with what use case do you get rpmrebuild.tar with 0 byte size. Does it happen during combirepo Deb package building? Or at combirepo runtime?

I executed
`$ python -m pip install stdeb --user
$ ./setup.py sdist
$ ./setup.py --command-packages=stdeb.command bdist_deb
After that it can be installed as follows:

$ sudo dpkg -i deb_dist/combirepo_*.deb`

as it is described in README.

**Comment by ilya-palachev** [comment]
Could you check that `rpmrebuild` submodule has been initialized? It can be done via `git submodules update` or smth. like that. Usual `git clone` doesn't clones submodules.

**Comment by a-lyupa** [comment]
On my host rpmrebuild sources appear when I execute
`git submodule init
 git submodule update`

Why rpmrebuild is located on git.code.sf.net? 

[submodule "combirepo/rpmrebuild"]
	path = rpmrebuild
	url = https://git.code.sf.net/p/rpmrebuild/git
	revision = .

**Comment by ilya-palachev** [comment]
Did it help?

> Why rpmrebuild is located on git.code.sf.net?

For the time when it we added it, it was the main repo of that tool.
