### ISSUE TITLE
Versions conflict

### ISSUE THREAD

**Issue by a-lyupa** [Samsung/combirepo#5]
There are different versions of libmm-sound in san- and unified- repos:
```
./combireposQZlEvrepository/armv7l/libmm-sound-sdk-devel-0.12.22-37.1.armv7l.rpm
./combireposQZlEvrepository/armv7l/libmm-sound-devel-0.12.22-37.1.armv7l.rpm
./combireposQZlEvrepository/armv7l/libmm-sound-0.12.22-37.1.armv7l.rpm
./combireposQZlEvrepository/armv7l/libmm-sound-tool-0.12.22-37.1.armv7l.rpm
./combirepo7mmhr5repository/armv7l/libmm-sound-tool-0.12.19-2.9.armv7l.rpm
./combirepo7mmhr5repository/armv7l/libmm-sound-0.12.19-2.9.armv7l.rpm
./combirepo7mmhr5repository/armv7l/libmm-sound-sdk-devel-0.12.19-2.9.armv7l.rpm
./combirepo7mmhr5repository/armv7l/libmm-sound-devel-0.12.19-2.9.armv7l.rpm`
```

`--preferring-strategy big` is set.

In case of  `--mirror` option an image is built successfully but in case of `--greedy` there is an error because of different versions of the same packages:
```
ERROR:root:Found 7 packages with different version numbers!
ERROR:root: libmm-sound                    0.12.22 0.12.19
...
ERROR:root:Please go and rebuild them!
```

@ilya-palachev , could you comment this case?

**Comment by ilya-palachev** [comment]
Hi, Anastasia.
Yes, it's a bit tricky heuristics :)

The reason is the following:
1. `--greedy` option means that `combirepo` marks the maximum set of packages, i.e. tries to get as many packages from marked ( = sanitized) repository as possible.
2. `--mirror` option means that `combirepo` gets non-marked packages instead of marked ones, if some package doesn't present in the marked repository.
3. The error `Found 7 packages with different version numbers!` is generated by method [check_rpm_versions](https://github.com/Samsung/combirepo/blob/cdd482b5c7bc2ef3e87e971663ab50cc57a22790/combirepo/repository_combiner.py#L115), which **checks only marked packages** for equality of version numbers (see [this](https://github.com/Samsung/combirepo/blob/cdd482b5c7bc2ef3e87e971663ab50cc57a22790/combirepo/repository_combiner.py#L228) line, where it's called). For each marked package this method checks its version number in marked and non-marked repository, and asks the developer to make them equal. If I recall correctly, at the stage of `combirepo` design and development this feature was needed to prevent image creation with different versions. This is needed to make debugging of package correct: if versions of the package are different, we cannot provide the correctness of its testing in the combined image.

As I guess, `libmm-sound-*` packages weren't marked when `--mirror` option was specified, because `ks` file didn't contain explicit mention of that packages. But with `--greedy` option, `libmm-sound-*` packages were marked, and repository combiner checked them for version correspondence.

So you have three options:
1. Actually rebuild `libmm-sound-*` packages in marked ( = sanitized) repository, so that to make versions correspond to each other.
2. Temporarily disable [check_rpm_versions](https://github.com/Samsung/combirepo/blob/cdd482b5c7bc2ef3e87e971663ab50cc57a22790/combirepo/repository_combiner.py#L115) and see to what consequences that will lead. I believe that either `mic` will fail during image creation phase, or there will be some run-time error. Moreover, as I remember, `mic` error logs about non-equal versions **are very strange and hard to debug**, because `mic` reports not the root cause of the error. There is some tricky way to debug it, I can describe if needed.
3. Implement heuristic that will exclude package from marked set, if there is a version conflict. I.e. take non-marked package if marked one has a version conflict.

Hope this comment will help.

**Comment by ilya-palachev** [comment]
One more option:
3. Implement heuristic that will exclude package from marked set, if there is a version conflict. I.e. take non-marked package if marked one has a version conflict.

**Comment by a-lyupa** [comment]
@ilya-palachev,
Thank you for a such detailed response!

**Comment by a-lyupa** [comment]
@ilya-palachev , @rayslava ,
What if replace critical error of version mismatch with warning, unmark such packages and continue building an image?

**Comment by rayslava** [comment]
I don't think that implicitly changing user request is a good idea. At least by default, may be we can add flag to convert it into warning.

**Comment by ilya-palachev** [comment]
Maybe, a trade-off would be, when both `--mirror` and `--greedy` options are specified, to take non-marked package when its version conflicts with marked one's.

**Comment by a-lyupa** [comment]
Added a new option to skip version mismatch
https://github.com/Samsung/combirepo/pull/9
