### ISSUE TITLE
Restricted count of parts

### ISSUE THREAD

**Issue by a-lyupa** [Samsung/combirepo#7]
Exception: This script is able to handle only all-in-one or three- or six-parted images!

@ilya-palachev , what is the reason of this restriction?

**Comment by ilya-palachev** [comment]
At the time when this feature was being implemented, three images required special handling (see [here](https://github.com/Samsung/combirepo/blob/b4d5095a4fef01b21175153959209a7e13e2c082/combirepo/temporaries.py#L142)):
```
    mount_image(directory, rootfs_image)
    system_directory = os.path.join(os.path.join(directory, "opt"))
    if not os.path.isdir(system_directory):
        os.mkdir(system_directory)
    mount_image(system_directory, system_image)
    user_directory = os.path.join(system_directory, "usr")
    if not os.path.isdir(user_directory):
        os.mkdir(user_directory)
    mount_image(user_directory, user_image)
```
because `rootfs.img` should be mounted to `/`, `system-data.img` to `/opt` and `user.img` to `/opt/usr`. So the `combirepo`'s abilities were explicitly restricted to one and three partition firmwares, because each new firmware structure should be handled in [`mount_firmware`](https://github.com/Samsung/combirepo/blob/b4d5095a4fef01b21175153959209a7e13e2c082/combirepo/temporaries.py#L153) in a special way.

So if now there is some uniform way to mount all images (for example, by using some external information about mount structure) it is OK to replace this behaviour with more modern behaviour. Otherwise it is recommended to implement each new structure's handling each time when it is met. Another way is to make this behaviour configurable, i.e. allow the user to specify mount points of different parts explicitly by some config or command line option(s).

**Comment by a-lyupa** [comment]
Ok, thanks!
Currently swap partition was added to rootfs, system-data, user triplet.

**Comment by ilya-palachev** [comment]
Seems that in this case a better solution would be to remove hard-coded paths in the `combirepo`, so that to make mount point locations configurable. The similar thing is done for repository _triplets_, and in the case of partitions it would be good to have _pairs_ like (`partition name`, `mount point path`), e.g. (`rootfs.img`, `/`).

**Comment by a-lyupa** [comment]
Good idea. I'd like to implement it later. Just for now I prepared a small fix https://github.com/Samsung/combirepo/pull/8

**Comment by a-lyupa** [comment]
Prepared patch to get images and mount points from kickstart file
https://github.com/Samsung/combirepo/pull/10
